name: Unit Tests and lints
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Jest Tests and Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm i
      - run: npm test
